syntax = "proto3";

package test.v1;

option go_package = "github.com/qhai-dev/yato/backend/kapis/test/v1";

// The greeting service definition.
service TestService {
  // Sends a greeting
  rpc SayHello(SayHelloRequest) returns (SayHelloResponse) {}
  // Sends another greeting
  rpc SayHelloAgain(SayHelloAgainRequest) returns (SayHelloAgainResponse) {}
}

// The request message containing the user's name.
message SayHelloAgainRequest {
  string name = 1;
}

// The response message containing the greetings
message SayHelloAgainResponse {
  string message = 1;
}

message SayHelloRequest {
  string name = 1;
}

message SayHelloResponse {
  string message = 1;
}
