load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    testonly = True,
    srcs = [
        "main.go",
        "wire.go",
    ],
    importpath = "github.com/qhai-dev/yato/backend/admin/main/manager/cmd",
    visibility = ["//visibility:private"],
    deps = [
        "//backend/admin/main/manager/internal/app",
        "//backend/library/framework",
    ],
)

go_binary(
    name = "cmd",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)
